import socket
import sys
import threading
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generalUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self, MainWindow, host, port):
        self.client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.client.connect((host, port))
        self.setupUi(MainWindow)
        self.run_receive()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 20, 381, 471))
        self.listWidget.setObjectName("listWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(332, 517, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 516, 271, 41))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.listWidget.insertItem(0, "输入用户昵称以开始聊天")
        self.pushButton.clicked.connect(self.send)
        self.lineEdit.returnPressed.connect(self.send)

    def send(self):
        msg = self.lineEdit.text().strip()
        self.client.send(msg.encode())
        self.lineEdit.clear()

    def receive(self):
        while True:
            msg = self.client.recv(1024).decode()
            self.listWidget.insertItem(self.listWidget.count(), msg)
            self.listWidget.scrollToBottom()

    def run_receive(self):
        thread = threading.Thread(target=self.receive)
        thread.daemon = True
        thread.start()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "网络聊天室客户端"))
        self.pushButton.setText(_translate("MainWindow", "发送"))


if __name__ == '__main__':
    host = 'localhost'
    port = 8888

    app = QtWidgets.QApplication(sys.argv)
    win = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(win, host, port)
    win.show()
    sys.exit(app.exec_())
